### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by oliversahr** [salto-io/salto#3179]
Hi,
I tried to connect salto to a zendesk environment using the following steps:

```
[oliversahr@Salto ~]$ salto --version
version 0.3.19, branch main, hash ef88d28a

[oliversahr@Salto ~]$ salto init
? Enter a name for the first environment in the workspace zendesk
Initiated empty workspace
Use `salto service add <service-name>` to add accounts to the environment

[oliversahr@Salto ~]$ salto service add zendesk_support
Please enter your Zendesk_support credentials:

? Username: <user>@mail.com
? Password: <password>
? subdomain (https://<your subdomain>.zendesk.com): <domain>

✔ Login information successfully updated!

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

Is something wrong with our Zendesk environment?

I can provide additional information if needed.

Thanks and best regards!
Oliver

**Comment by oliversahr** [comment]
Relevant line with verbose logging:

```
2022-07-14T13:32:56.760Z error oliversahr/Distrobox/Salto/cli Caught exception: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at ReaddirpStream._formatEntry (webpack://@salto-io/cli/../../node_modules/readdirp/index.js?:176:48)
    at eval (webpack://@salto-io/cli/../../node_modules/readdirp/index.js?:124:67)
    at Array.map (<anonymous>)
    at ReaddirpStream._read (webpack://@salto-io/cli/../../node_modules/readdirp/index.js?:124:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by oliversahr** [comment]
Solved! Don't run the program in the folder you're currently in, the executable has to be in a separate folder.
